server:
  port: 8888
spring:
  apllication:
    name: greeting-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/leandro-felipe/config-server.git
          default-label: main
          search-paths:
          - "greeting-service*"
